version: '3.8'

services:
  backend:
    image: chenhexu/bluebank-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    volumes:
      - bank_data:/app/data
    networks:
      - bank_network

  frontend:
    image: chenhexu/bluebank-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - bank_network

volumes:
  bank_data:

networks:
  bank_network:
    driver: bridge 